=== i2group/notebook-sdk/schemas/plugin-manifest.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://i2group.github.io/notebook-sdk/schemas/plugin-manifest.json",
  "type": "object",
  "title": "The JSON manifest for an i2 Notebook plug-in.",
  "required": ["pluginId", "pluginVersion", "name", "entryPointUrl"],
  "properties": {
    "$schema": { "type": "string" },
    "pluginId": {
      "type": "string",
      "title": "The identifier of the plug-in, as a lower-case GUID.",
      "minLength": 36,
      "maxLength": 36,
      "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}",
      "examples": ["01234567-89ab-cdef-0123-456789abcdef"]
    },
    "pluginVersion": {
      "type": "string",
      "title": "The version of the plug-in.",
      "minLength": 1,
      "examples": ["1.0"]
    },
    "name": {
      "type": "string",
      "title": "The name of the plug-in, which might appear in status messages.",
      "minLength": 1,
      "examples": ["My i2 Notebook plug-in"]
    },
    "entryPointUrl": {
      "type": "string",
      "title": "The URL of the plug-in entry point JavaScript file, relative to the manifest.",
      "minLength": 1,
      "examples": ["./entrypoint.js"]
    },
    "entryPointCsp": {
      "title": "Directives to add to the HTTP Content-Security-Policy for the page hosting the entry point.",
      "$ref": "#/definitions/csp"
    },
    "toolViewCsp": {
      "title": "Directives to add to the HTTP Content-Security-Policy for tool views.",
      "$ref": "#/definitions/csp"
    }
  },
  "definitions": {
    "csp": {
      "type": "object",
      "title": "Directives to add to the HTTP Content-Security-Policy response header.",
      "default": {},
      "examples": [
        {
          "connect-src": "http://external-server-to-access-from-script",
          "style-src": "'unsafe-inline'"
        }
      ],
      "patternProperties": {
        ".*": { "type": "string", "minLength": 1 }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== i2group/notebook-sdk/samples/item-type-plugin/public/plugin.json
{
  "$schema": "https://i2group.github.io/notebook-sdk/schemas/plugin-manifest.json",
  "name": "item-type-plugin",
  "pluginId": "ac7bcb47-f3d5-45c8-8d41-8ca30cf8ec06",
  "pluginVersion": "1.0.0",
  "entryPointUrl": "./entrypoint.js",
  "entryPointCsp": {
    "script-src": "'unsafe-eval'",
    "connect-src": "*"
  },
  "toolViewCsp": {
    "script-src": "'unsafe-eval' 'unsafe-inline'",
    "style-src": "'unsafe-inline'",
    "connect-src": "*"
  }
}

=== i2group/notebook-sdk/samples/angular-plugin/src/plugin.json
{
  "$schema": "https://i2group.github.io/notebook-sdk/schemas/plugin-manifest.json",
  "pluginId": "3c789949-1955-4d4e-93fe-b5718effc325",
  "name": "My i2 Notebook plug-in",
  "pluginVersion": "1.0.0",
  "entryPointUrl": "./entrypoint.js",
  "toolViewCsp": {
    "style-src": "'unsafe-inline'"
  }
}

=== i2group/notebook-sdk/samples/color-plugin-new/public/plugin.json
{
  "$schema": "https://i2group.github.io/notebook-sdk/schemas/plugin-manifest.json",
  "name": "color-plugin",
  "pluginId": "73623dbf-294d-4035-973b-24dc3badaad7",
  "pluginVersion": "1.0.0",
  "entryPointUrl": "./entrypoint.js",
  "entryPointCsp": {
    "script-src": "'unsafe-eval'",
    "connect-src": "*"
  }
}

=== i2group/notebook-sdk/samples/vue-plugin/public/plugin.json
{
  "$schema": "https://i2group.github.io/notebook-sdk/schemas/plugin-manifest.json",
  "name": "My i2 Notebook plug-in",
  "pluginId": "94f22ca7-6a90-4463-844f-90534aed2a9c",
  "pluginVersion": "1.0.0",
  "entryPointUrl": "./entrypoint.js",
  "toolViewCsp": {
    "style-src": "'unsafe-inline'"
  }
}

=== i2group/notebook-sdk/samples/react-plugin/public/plugin.json
{
  "$schema": "https://i2group.github.io/notebook-sdk/schemas/plugin-manifest.json",
  "name": "My i2 Notebook plug-in",
  "pluginId": "00000000-0000-0000-0000-000000000001",
  "pluginVersion": "1.0.0",
  "entryPointUrl": "./entrypoint.js",
  "toolViewCsp": {
    "script-src": "'unsafe-inline'",
    "style-src": "'unsafe-inline'"
  }
}

=== i2group/notebook-sdk/samples/dialog-sample-plugin/public/plugin.json
{
  "$schema": "https://i2group.github.io/notebook-sdk/schemas/plugin-manifest.json",
  "name": "dialog-sample-plugin",
  "pluginId": "dff93a38-4e4d-49f7-a4f0-3dc27060ed10",
  "pluginVersion": "1.0.0",
  "entryPointUrl": "./entrypoint.js",
  "entryPointCsp": {
    "script-src": "'unsafe-eval'",
    "connect-src": "*"
  },
  "toolViewCsp": {
    "script-src": "'unsafe-eval' 'unsafe-inline'",
    "style-src": "'unsafe-inline'",
    "connect-src": "*"
  }
}
